version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
   install:
      - requirements: doc/requirements-rtd.txt
        # no - method: pip here, -e . is already in doc/requirements-rtd.txt
